module.exports = {
	siteURL: process.env.URL || 'https://nahebaugmbh.de',
	siteName: 'NaheBau GmbH',
	siteDescription: 'NaheBau GmbH - Bau- und Renovierungsarbeiten in Bad Kreuznach',
	siteImage: '/assets/images/logo.jpg',
	lang: 'de',
	locale: 'de_de',
	authorName: 'Sven Hoffmann',
	authorURL: 'sven-hoffmann',
	authorEmail: 'sven.hoffmann@nahebaugmbh.de',
	twitterSite: '@shanerobinson',
	twitterCreator: '@shanerobinson',
	address: {
		street: 'Guldentaler Weg 8',
		city: 'Bad Kreuznach',
		state: 'Hessen',
		zip: '55545',
		phoneDisplay: '+49 (176) 122-5656',
		phoneCall: '+491761225656',
		email: 'sven.hoffmann@nahebaugmbh.de',
	},
}
